# Generated by Django 5.1.1 on 2024-09-08 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_compra_data_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data_compra',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='compra',
            name='metodo_pagamento',
            field=models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('Pix', 'Pix'), ('Outro', 'Outro')], max_length=20),
        ),
    ]
