# Generated by Django 5.1.1 on 2024-09-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_compra_data_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Tecnologia', 'Tecnologia'), ('Alimentação', 'Alimentação'), ('Cuidado pessoal', 'Cuidado Pessoal'), ('Transporte', 'Transporte'), ('Vestuário', 'Vestuário'), ('Contratação de serviço', 'Contratação de serviço'), ('Outro', 'Outro')], max_length=30),
        ),
        migrations.AddField(
            model_name='compra',
            name='nivel_utilidade',
            field=models.CharField(blank=True, choices=[('Fútil', 'Fútil'), ('Útil necessário', 'Útil necessário'), ('Útil não necessário', 'Útil não necessário')], max_length=30),
        ),
        migrations.AlterField(
            model_name='compra',
            name='metodo_pagamento',
            field=models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('Pix', 'Pix'), ('Boleto', 'Boleto'), ('Outro', 'Outro')], max_length=20),
        ),
    ]
