# Generated by Django 5.1.1 on 2024-09-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('data_compra', models.DateTimeField(auto_now=True)),
                ('metodo_pagamento', models.CharField(max_length=100)),
            ],
        ),
    ]
