# Generated by Django 5.1.1 on 2024-09-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_compra_categoria_compra_nivel_utilidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='descricao',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
