# Generated by Django 5.1.1 on 2024-10-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_compra_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Tecnologia', 'Tecnologia'), ('Alimentação', 'Alimentação'), ('Cuidado pessoal', 'Cuidado Pessoal'), ('Transporte', 'Transporte'), ('Vestuário', 'Vestuário'), ('Saúde', 'Saúde'), ('Lazer', 'Lazer'), ('Moradia', 'Moradia'), ('Educação', 'Educação'), ('Contratação de serviço', 'Contratação de serviço'), ('Outro', 'Outro')], default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='compra',
            name='descricao',
            field=models.CharField(blank=True, default='-', max_length=150),
        ),
        migrations.AlterField(
            model_name='compra',
            name='nivel_utilidade',
            field=models.CharField(blank=True, choices=[('Fútil', 'Fútil'), ('Útil e necessário', 'Útil e necessário'), ('Útil, porém não necessário', 'Útil, porém não necessário')], default='-', max_length=30),
        ),
    ]
